hs.loadSpoon("SpoonInstall")
spoon.SpoonInstall:andUse("ReloadConfiguration", { start = true })
hs.alert.show("Hammerspoon reloaded")
screenWatcher = hs.screen.watcher.new(function()
    hs.timer.doAfter(2, function() hs.reload() end)
end):start()
require("config.help")
require("config.ryoiki")
require("config.hanten")
require("config.jinrai")
require("config.tomonari")
require("config.muryokusho")
