hs.loadSpoon("SpoonInstall")
spoon.SpoonInstall:andUse("ReloadConfiguration", { start = true })
hs.alert.show("Hammerspoon reloaded")
hs.hotkey.bind({ "option", "shift", "cmd", "ctrl" }, "r", function()
	hs.reload()
end)
require("config.help")
require("config.ryoiki")
require("config.hanten")
require("config.jinrai")
require("config.muryokusho")
