hs.loadSpoon("SpoonInstall")
spoon.SpoonInstall:andUse("ReloadConfiguration", { start = true })
require("config.help")
require("config.ryoiki")
require("config.hanten")
require("config.jinrai")
require("config.tomonari")
require("config.muryokusho")
